using System;

#nullable disable

namespace Domain.Entities.Fenix
{
    public partial class Solicitud
    {
        public int Id { get; set; }
        public int? IdSolicitud { get; set; }
        public int? IdBuro { get; set; }
        public DateTime? FechaSolicitud { get; set; }
        public DateTime? FechaIngreso { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public string UsrModifica { get; set; }
        public int? IdPersona { get; set; }
        public int? Status { get; set; }
        public DateTime? FechaTransferencia { get; set; }
        public string Comentarios { get; set; }
        public string UsoCredito { get; set; }
        public bool? Consentimiento { get; set; }
        public int? IdProducto { get; set; }
        public int? IdAgente { get; set; }
        public int? SoporteTipo { get; set; }
        public int? IdStatusOrden { get; set; }
        public bool? FotoCedula { get; set; }
        public bool? Recibo { get; set; }
        public bool? Contrato { get; set; }
        public bool? Pagare { get; set; }
        public bool? ReciboIngresos { get; set; }
        public bool? CuentaBancaria { get; set; }
        public bool? Selfie { get; set; }
        public string Origen { get; set; }
        public string IdUsrAsig { get; set; }
        public int? IdEstadoProc { get; set; }
        public int? SubStatus { get; set; }
        public decimal? MontoMaximo { get; set; }
        public int? Score { get; set; }
        public bool? ForzamientoSolicitud { get; set; }
        public string UsuarioModificacion { get; set; }
        public int? VersionScore { get; set; }
        public string UrlFotoCedula { get; set; }
        public string UrlFotoSelfie { get; set; }
        public string FotoFirma { get; set; }
        public int? Pin { get; set; }
        public string UrlFotoCedulaTrasera { get; set; }
        public int? IdResultCompareFace { get; set; }
        public string ResultTextCed { get; set; }
        public bool? ResultTextCedTras { get; set; }
        public bool? ApruebaGini { get; set; }
        public bool? ApruebaRules { get; set; }
        public string UsrGeneraConPaga { get; set; }
        public DateTime? FechaGeneraPagare { get; set; }
        public string UrlDirectorioPagare { get; set; }
        public bool? ProcesoPayBac { get; set; }
        public int? IdDetectedText { get; set; }
        public DateTime? FechaAsignacion { get; set; }
        public int? IdEstado { get; set; }
        public int? Asignado { get; set; }
        public DateTime? FechaProcesamiento { get; set; }
        public string UsuarioAsignado { get; set; }
        public DateTime? FechaAsignacionVentas { get; set; }
        public bool? AsignarCola { get; set; }
        public bool? Renovacion { get; set; }
        public bool? BndListaNegra { get; set; }
        public string Matriz { get; set; }
        public int? BndIntentosRechazo { get; set; }
        public DateTime? FechaReintento { get; set; }
        public string UsuarioEnviaVenta { get; set; }
        public string SubOrigen { get; set; }
        public int? ContLlamadas { get; set; }
        public int? BndTransferencia { get; set; }
        public string UrlDomiciliacion { get; set; }
        public DateTime? FechaEnviaVenta { get; set; }
        public bool BndRevisionDomiciliacion { get; set; }
        public string ComentarioRevisionDomiciliacion { get; set; }
        public bool? DebitoAutomatico { get; set; }
        public DateTime? FechaDebitoAutomatico { get; set; }
        public string UsrDebitoAutomatico { get; set; }
        public decimal? DisponibleCuota { get; set; }
        public string MotivoRechazo { get; set; }
        public bool? BitAprobadaExcepcion { get; set; }
        public string IdFacebook { get; set; }
        public string IdVendedor { get; set; }
        public bool? ApruebaFlex { get; set; }
        public long? ScorePrincipalFlex { get; set; }
        public long? ScoreDiferenciadoFlex { get; set; }
        public long? IdPlanFinanciero { get; set; }
        public int? IdCicloPago { get; set; }
        public decimal? Cuota { get; set; }
        public decimal? MontoFinanciado { get; set; }
        public decimal? MontoOriginacion { get; set; }
        public long? IdPlanesMedidaPlazo { get; set; }
        public DateTime? FechaPrimerPago { get; set; }
        public DateTime? FechaUltimoPago { get; set; }
        public string AgenteVentaZenziya { get; set; }
        public string IdAgencia { get; set; }
        public bool? Ampliacion { get; set; }
        public bool? Bases { get; set; }
        public bool? ApruebaUnderWrite { get; set; }
        public string ComentarioZenziya { get; set; }
        public string ComentarioComercio { get; set; }
        public long? ScorePrincipalFlexRecalibrado { get; set; }
        public long? ScoreDiferenciadoFlexRecalibrado { get; set; }
        public int TipoCredito { get; set; }
        public string UrlDocMovist { get; set; }
        public string IdNuevoOrigen { get; set; }
        public string Marca { get; set; }
        public bool? MoraTuca { get; set; }
        public int? IdPoliticaCredito { get; set; }
        public bool? EstadoSugef { get; set; }
        public DateTime? FechaSugef { get; set; }
        public int? FkIdArbolDecision { get; set; }
        public int? StatusOriginal { get; set; }
        public decimal? ScorePrimarios { get; set; }
        public decimal? ScorePrimariosVersion { get; set; }
    }
}
